# Generated by Django 5.2.3 on 2025-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для клиентов'),
        ),
    ]
