# Generated by Django 5.2.3 on 2025-06-27 02:32

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Введите корректный номер телефона.')], verbose_name='Телефон')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('user', 'User')], default='user', max_length=20, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('preferred_language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('user_timezone', models.CharField(default='Asia/Bishkek', max_length=50, verbose_name='Часовой пояс')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа')),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP адрес последнего входа')),
                ('last_login_device', models.CharField(blank=True, max_length=255, null=True, verbose_name='Устройство входа')),
                ('last_login_device_time', models.DateTimeField(blank=True, null=True, verbose_name='Время входа с устройства')),
                ('country', models.CharField(default='Кыргызстан', max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('agree_to_terms', models.BooleanField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employees_count', models.CharField(blank=True, max_length=10, null=True)),
                ('sphere', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('specialists_count', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
