# Generated by Django 5.2.3 on 2025-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tariff_user_is_trial_user_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tariff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_tarifed',
            field=models.BooleanField(default=True, verbose_name='Тариф активен'),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
