# Generated by Django 5.2.3 on 2025-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_tariff_user_is_tarifed_delete_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dashboard_welcome_showed',
            field=models.BooleanField(default=False, verbose_name='Показан welcome-заглушка Dashboard'),
        ),
    ]
