# Generated by Django 5.2.3 on 2025-06-28 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_instagram_business_phone_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.IntegerField(choices=[(15, '15 минут'), (30, '30 минут'), (45, '45 минут'), (60, '60 минут')], default=60, verbose_name='Длительность слота по умолчанию (минуты)')),
                ('buffer_time', models.IntegerField(choices=[(0, 'Без буфера'), (5, '5 минут'), (10, '10 минут'), (15, '15 минут')], default=0, verbose_name='Буферное время (минуты)')),
                ('auto_confirm_bookings', models.BooleanField(default=True, verbose_name='Автоматическое подтверждение бронирований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='businesses.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Настройки бронирования',
                'verbose_name_plural': 'Настройки бронирования',
            },
        ),
        migrations.CreateModel(
            name='BusinessNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Уведомления по Email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS уведомления')),
                ('whatsapp_notifications', models.BooleanField(default=False, verbose_name='Уведомления WhatsApp')),
                ('telegram_notifications', models.BooleanField(default=True, verbose_name='Уведомления Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='businesses.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений бизнеса',
                'verbose_name_plural': 'Настройки уведомлений бизнесов',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Уведомления по Email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS уведомления')),
                ('whatsapp_notifications', models.BooleanField(default=False, verbose_name='Уведомления WhatsApp')),
                ('telegram_notifications', models.BooleanField(default=True, verbose_name='Уведомления Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Авто')], default='light', max_length=20, verbose_name='Тема оформления')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('timezone', models.CharField(default='Asia/Bishkek', max_length=50, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
