# Generated by Django 5.2.3 on 2025-07-02 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedashboard',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeenotification',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeClient',
        ),
        migrations.DeleteModel(
            name='EmployeeDashboard',
        ),
        migrations.DeleteModel(
            name='EmployeeNotification',
        ),
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
