# Generated by Django 5.2.3 on 2025-07-02 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_remove_employeedashboard_employee_and_more'),
        ('employees', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAIAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='bot', max_length=50, verbose_name='Иконка')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'ИИ-совет сотрудника',
                'verbose_name_plural': 'ИИ-советы сотрудников',
                'unique_together': {('employee', 'title')},
            },
        ),
    ]
