# Generated by Django 5.2.3 on 2025-06-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_instagram_business_phone_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, unique=True)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('website_bookings_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='businesses.business')),
            ],
        ),
    ]
