# Generated by Django 5.2.3 on 2025-06-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20250628_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Сайт бизнеса', 'verbose_name_plural': 'Сайты бизнесов'},
        ),
        migrations.AlterField(
            model_name='website',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество бронирований'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=100, unique=True, verbose_name='URL сайта'),
        ),
        migrations.AlterField(
            model_name='website',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_bookings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Бронирования через сайт'),
        ),
        migrations.CreateModel(
            name='WebsiteBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('specialist', models.CharField(blank=True, max_length=100, null=True, verbose_name='Специалист')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('time', models.CharField(max_length=20, verbose_name='Время')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='website.website')),
            ],
            options={
                'verbose_name': 'Бронирование с сайта',
                'verbose_name_plural': 'Бронирования с сайта',
            },
        ),
    ]
