# Generated by Django 5.2.3 on 2025-06-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_last_visit_remove_client_total_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма покупок'),
        ),
        migrations.AddField(
            model_name='client',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего визитов'),
        ),
    ]
