# Generated by Django 5.2.3 on 2025-06-27 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('business_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='businesses.businesssubtype', verbose_name='Субкатегория бизнеса')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='Образование')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('schedule', models.CharField(blank=True, max_length=100, verbose_name='График')),
                ('clientsCount', models.PositiveIntegerField(default=0, verbose_name='Клиентов')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('passportNumber', models.CharField(blank=True, max_length=50, verbose_name='Номер паспорта')),
                ('passportIssued', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passportExpiry', models.DateField(blank=True, null=True, verbose_name='Срок действия паспорта')),
                ('taxId', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('bankAccount', models.CharField(blank=True, max_length=50, verbose_name='Номер счета')),
                ('bankName', models.CharField(blank=True, max_length=100, verbose_name='Название банка')),
                ('emergencyContact', models.CharField(blank=True, max_length=20, verbose_name='Телефон экстренного контакта')),
                ('emergencyContactName', models.CharField(blank=True, max_length=100, verbose_name='Имя экстренного контакта')),
                ('emergencyContactRelation', models.CharField(blank=True, max_length=100, verbose_name='Отношение экстренного контакта')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('contractNumber', models.CharField(blank=True, max_length=100, verbose_name='Номер контракта')),
                ('contractExpiry', models.DateField(blank=True, null=True, verbose_name='Срок действия контракта')),
                ('vacationDaysTotal', models.PositiveIntegerField(default=28, verbose_name='Всего дней отпуска')),
                ('vacationDaysUsed', models.PositiveIntegerField(default=0, verbose_name='Использовано дней отпуска')),
                ('sickDaysTotal', models.PositiveIntegerField(default=30, verbose_name='Всего больничных дней')),
                ('sickDaysUsed', models.PositiveIntegerField(default=0, verbose_name='Использовано больничных дней')),
                ('certifications', models.TextField(blank=True, verbose_name='Сертификаты')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Языки')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('insuranceNumber', models.CharField(blank=True, max_length=100, verbose_name='Номер страховки')),
                ('insuranceExpiry', models.DateField(blank=True, null=True, verbose_name='Срок действия страховки')),
                ('performanceReviews', models.JSONField(blank=True, default=list, verbose_name='Оценки работы')),
                ('trainingHistory', models.JSONField(blank=True, default=list, verbose_name='История обучения')),
                ('workSchedule', models.JSONField(blank=True, default=dict, verbose_name='График работы')),
                ('salaryHistory', models.JSONField(blank=True, default=list, verbose_name='История зарплат')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Документы')),
                ('is_master', models.BooleanField(default=False, verbose_name='Является мастером')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business', verbose_name='Бизнес')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emploee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
