# Generated by Django 5.2.3 on 2025-07-08 10:07

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='achievements',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bankAccount',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bankName',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='certifications',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contractExpiry',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Срок действия контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contractNumber',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergencyContact',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Телефон экстренного контакта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergencyContactName',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Имя экстренного контакта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergencyContactRelation',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Отношение экстренного контакта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='equipment',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insuranceExpiry',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Срок действия страховки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insuranceNumber',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Номер страховки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='languages',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportExpiry',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Срок действия паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportIssued',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportNumber',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='schedule',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startDate',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='taxId',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='ИНН'),
        ),
    ]
