# Generated by Django 5.2.3 on 2025-06-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('price', models.PositiveIntegerField(help_text='Фактическая стоимость услуги', verbose_name='Стоимость (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(limit_choices_to={'is_master': True}, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['date', 'master'], name='schedules_b_date_95f9a9_idx')],
                'unique_together': {('master', 'date', 'start_time')},
            },
        ),
    ]
